
server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver               # mysql驱动包 com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.72.100:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: reader
    password: 123456

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities    # 所有Entity别名类所在包

